### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by dylanxps** [Elementars/Xulu-v1.5.2#1]
what clients is it not compatible with?

**Comment by cherosin** [comment]
t

**Comment by supakeks** [comment]
find out yourself lol

**Comment by dylanxps** [comment]
> find out yourself lol

im not deleting future retard, lol

**Comment by supakeks** [comment]
> > find out yourself lol
> 
> im not deleting future retard, lol

I literally never said to stop using future, I just said to find out yourself, it's not like if Xulu crashes with Future you'll never be able to play Minecraft again, just give it a try

**Comment by Elementars** [comment]
xulu shouldn't crash with future although some future mods may override xulu and vice versa
