### ISSUE TITLE
Skidded client

### ISSUE THREAD

**Issue by x0XP** [Elementars/Xulu-v1.5.2#10]
How is this client back on Github after I DMCA'd the f**k out of it like 4 years ago?
It's a skidded client and stole most of its code from the Xdolf client myself and Sgt. Pepper made and actually managed to make it worse.
Either take this down or I'll be sending another DMCA request.

**Comment by Elementars** [comment]
I think you're confused, this has nothing to do with Sliz's Xulu for 1.11 besides the name

**Comment by x0XP** [comment]
Umm dude I've checked over a lot of the source code. This is still Xdolf copy & paste. The module base is exactly the same along with the code for many other mods. Take down or it's DMCA time this is my last warning.
