### ISSUE TITLE
My previous issue still stands - this is a skidded client and I will DMCA strike if you ignore me again

### ISSUE THREAD

**Issue by x0XP** [Elementars/Xulu-v1.5.2#11]
How is this client back on Github after I **DMCA'd** the f**k out of it like 4 years ago?
It's a skidded client and stole most of its code from the **Xdolf** client **myself** and **Sgt. Pepper** made and actually managed to make it worse.
Either take this down or I'll be sending _another_ **DMCA** request.

In response to you claiming it's not, I've been over the code extensively, lots of this is _still_ code that has been stripped and **stolen** from **Xdolf**, except you've added an Event Manager in the middle of it all and it looks an absolute terrible mess because you're literally using the base for a client I wrote in **2013**.

I'd be okay with a little credit to state where you've skidded 50% of your client from but as you didn't do that and have now **refused to listen to my request**, I'm going to leave it **48** hours for you to give me a real response else I will be striking down this repository.

My contact handle on Discord is **x0XP#4202**, feel free to contact me - if we can come to a financially beneficial arrangement then I may change my mind.

As an adding bonus, just so you're aware I'll also be taking down any and all YouTube videos that are using a reskinned version of my client, I've done this before with Xulu as seen here https://i.imgur.com/d3sz2L0.png and I will be doing this with this version also - this isn't even up for debate.

**Comment by Elementars** [comment]
The only thing that isn't up for **debate** is the font renderer, which I have now committed to the README (as you have noted above is fine). Nothing else in this client has been influenced by Xdolf/Xulu 1.11 and I stand my **ground** on that statement. Quite the **power trip** with that bonus if you're even trying to claim ownership of my videos which is completely _incorrect_, as I created the content, the client, and the branding. 

Financial compensation isn't even appropriate as neither your **outdated** Xdolf nor Xulu were **paid** clients.

Have a good day.
