### ISSUE TITLE
dream is gei

### ISSUE THREAD

**Issue by Tiffycake** [Elementars/Xulu-v1.5.2#5]
is this a client or a fabric mod or another thing cuz i duno how to install it

**Comment by Elementars** [comment]
Forge mod, it won't be fabric since it is a 1.12.2 mod

**Comment by Tiffycake** [comment]
isnt there a 1.16.4 xulu version

**Comment by Elementars** [comment]
no

**Comment by raaaphiii** [comment]
is there a coordinate hud option, if so i cant find it

**Comment by Tiffycake** [comment]
are u planing to make one ?
